# Generated by Django 3.2.3 on 2021-07-12 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210712_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_flight',
            old_name='destination',
            new_name='To',
        ),
        migrations.RenameField(
            model_name='add_flight',
            old_name='date_posted',
            new_name='check_in_date',
        ),
        migrations.AddField(
            model_name='add_flight',
            name='check_out_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='add_flight',
            name='class_avaiable',
            field=models.DecimalField(decimal_places=0, default=3, max_digits=1),
        ),
    ]
