# Generated by Django 3.2.3 on 2021-07-17 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aircraft', '0001_initial'),
        ('blog', '0004_auto_20210712_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_flight',
            old_name='class_avaiable',
            new_name='class_available',
        ),
        migrations.AddField(
            model_name='add_flight',
            name='plane',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aircraft.addaircraft'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.add_flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
