# Generated by Django 3.2.3 on 2021-07-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210717_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_flight',
            name='class_available',
        ),
        migrations.AddField(
            model_name='booking',
            name='classes',
            field=models.CharField(choices=[('economey', 'economey'), ('first', 'first'), ('luxury', 'luxury'), ('premium', 'premium')], default='economey', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=0, default=600, max_digits=5),
        ),
    ]
